version: "3.8"
services:
  mongo: # https://hub.docker.com/_/mongo
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root # Change to variable under using docker secrets before deployment
      ME_CONFIG_MONGODB_ADMINPASSWORD: example # Change to variable before deployment
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
networks:
    default:
        name: nunet
